import type { ProductView } from "./types";

export const mockProducts: ProductView[] = [
  {
    id: "nike-air-max-270",
    name: "Air Max 270",
    category: "Running Shoes",
    description: "Features Nike's first lifestyle Air unit, delivering style, comfort and big attitude in a sleek silhouette. Perfect for daily wear and casual jogging.",
    image_url: "https://images.unsplash.com/photo-1542291026-7eec264c27ff",
    brand: "Nike",
    price: 120,
    rating: 4.8,
    emoji: "👟",
    company: "Nike",
    model: "Air Max Series",
    docs: 4,
    sessions: 1205,
    resolutionRate: 94,
    manufacturer: "Nike Inc.",
    year: "2023 - Present",
    productType: "Athletic Footwear",
    featured: true,
    commonIssues: ["Sizing running small", "Air bubble deflation", "Heel collar friction", "Sole grip wear"],
    documentation: [
      { icon: "📘", name: "Sizing & Fit Guide", meta: "PDF · 5 pages · Indexed" },
      { icon: "🔧", name: "Care & Cleaning Reference", meta: "PDF · 8 pages · Indexed", featured: true },
    ]
  },
  {
    id: "iphone-15-pro",
    name: "iPhone 15 Pro",
    category: "Electronics",
    description: "Forged in titanium and featuring the groundbreaking A17 Pro chip, a customizable Action button, and the most powerful iPhone camera system ever.",
    image_url: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9",
    brand: "Apple",
    price: 999,
    rating: 4.9,
    emoji: "📱",
    company: "Apple",
    model: "15 Pro",
    docs: 15,
    sessions: 8431,
    resolutionRate: 92,
    manufacturer: "Apple Inc.",
    year: "2023 - Present",
    productType: "Smartphone",
    featured: true,
    commonIssues: ["Battery drain on iOS 17", "Device warm during charging", "Action button unresponsive", "Wi-Fi connectivity drops"],
    documentation: [
      { icon: "📘", name: "User Guide & Basics", meta: "PDF · 142 pages · Indexed" },
      { icon: "🔧", name: "Apple Authorized Repair Manual", meta: "PDF · 210 pages · Indexed", featured: true },
    ]
  },
  {
    id: "sony-wh1000xm5",
    name: "WH-1000XM5 Headphones",
    category: "Electronics",
    description: "Sony's flagship active noise-canceling wireless headphones with dual processors controlling 8 microphones for unparalleled noise reduction.",
    image_url: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e",
    brand: "Sony",
    price: 398,
    rating: 4.7,
    emoji: "🎧",
    company: "Sony",
    model: "WH-1000XM5",
    docs: 8,
    sessions: 2190,
    resolutionRate: 89,
    manufacturer: "Sony Corp.",
    year: "2022 - Present",
    productType: "Over-Ear Headphones",
    commonIssues: ["Bluetooth multipoint sync lag", "ANC strength fluctuation", "Touch sensor unresponsive in cold", "Auto-pause feature false triggers"],
    documentation: [
      { icon: "📘", name: "Instruction Guide", meta: "PDF · 48 pages · Indexed" },
      { icon: "🔧", name: "Calibration & Reset Reference", meta: "PDF · 12 pages · Indexed", featured: true },
    ]
  },
  {
    id: "dell-xps-13",
    name: "XPS 13 Laptop",
    category: "Electronics",
    description: "Stunning 4-sided InfinityEdge display with Intel Core Ultra processors in an incredibly thin, lightweight CNC aluminum chassis.",
    image_url: "https://images.unsplash.com/photo-1593642632823-8f785ba67e45",
    brand: "Dell",
    price: 1099,
    rating: 4.6,
    emoji: "💻",
    company: "Dell",
    model: "XPS 9320",
    docs: 10,
    sessions: 3105,
    resolutionRate: 88,
    manufacturer: "Dell Technologies",
    year: "2023 - Present",
    productType: "Ultrabook",
    commonIssues: ["Touchpad gesture recognition", "Fan noise under heavy load", "Thermal throttling on battery", "External display connection drop"],
    documentation: [
      { icon: "📘", name: "Setup and Specifications Manual", meta: "PDF · 64 pages · Indexed" },
      { icon: "🔧", name: "Dell Service & Parts Manual", meta: "PDF · 112 pages · Indexed", featured: true },
    ]
  },
  {
    id: "dyson-v15-detect",
    name: "V15 Detect Cordless Vacuum",
    category: "Appliances",
    description: "Most powerful, intelligent cordless vacuum cleaner. Laser reveals microscopic dust, and acoustic piezo sensor counts particles to auto-adjust suction.",
    image_url: "https://images.unsplash.com/photo-1558317374-067fb5f30001",
    brand: "Dyson",
    price: 749,
    rating: 4.8,
    emoji: "🧹",
    company: "Dyson",
    model: "V15 Detect",
    docs: 6,
    sessions: 1420,
    resolutionRate: 91,
    manufacturer: "Dyson Ltd.",
    year: "2022 - Present",
    productType: "Stick Vacuum",
    commonIssues: ["Laser diode dirty error", "Filter clogged warning blinking", "Battery runtime drop in Boost mode", "Brush bar obstruction warning"],
    documentation: [
      { icon: "📘", name: "Quick Start Guide & Assembly", meta: "PDF · 28 pages · Indexed" },
      { icon: "🔧", name: "Piezo Sensor Maintenance Manual", meta: "PDF · 16 pages · Indexed", featured: true },
    ]
  },
  {
    id: "yeti-rambler-20",
    name: "Rambler 20 oz Tumbler",
    category: "Appliances",
    description: "Double-wall vacuum insulated tumbler keeping your favorite beverages hot or cold for hours, complete with the MagSlider Lid.",
    image_url: "https://images.unsplash.com/photo-1576092768241-dec231879fc3",
    brand: "Yeti",
    price: 35,
    rating: 4.9,
    emoji: "🥤",
    company: "Yeti",
    model: "Rambler 20oz",
    docs: 2,
    sessions: 410,
    resolutionRate: 98,
    manufacturer: "Yeti Coolers",
    year: "2021 - Present",
    productType: "Insulated Drinkware",
    commonIssues: ["MagSlider slider friction", "Dishwasher marks on DuraCoat", "Lid gasket seal leak"],
    documentation: [
      { icon: "📘", name: "Usage and Cleaning Directions", meta: "PDF · 4 pages · Indexed" }
    ]
  },
  {
    id: "patagonia-torrentshell",
    name: "Torrentshell 3L Jacket",
    category: "Apparel",
    description: "Simple and unpretentious H2No Performance Standard 3-layer rain jacket providing long-term waterproof/breathable comfort.",
    image_url: "https://images.unsplash.com/photo-1544923246-77307dd654cb",
    brand: "Patagonia",
    price: 149,
    rating: 4.7,
    emoji: "🧥",
    company: "Patagonia",
    model: "Torrentshell 3L",
    docs: 3,
    sessions: 620,
    resolutionRate: 95,
    manufacturer: "Patagonia Inc.",
    year: "2022 - Present",
    productType: "Rain Jacket",
    commonIssues: ["DWR coating wear over time", "Main zipper snagging", "Pit-zip leakage under heavy storm"],
    documentation: [
      { icon: "📘", name: "Washing and Re-waterproofing Guide", meta: "PDF · 6 pages · Indexed" }
    ]
  },
  {
    id: "rolex-submariner",
    name: "Submariner Date Watch",
    category: "Accessories",
    description: "The classic luxury divers' watch, featuring a rotatable Cerachrom bezel insert in ceramic, solid Oyster link bracelet, and chronometer grade caliber 3235.",
    image_url: "https://images.unsplash.com/photo-1523275335684-37898b6baf30",
    brand: "Rolex",
    price: 10500,
    rating: 4.9,
    emoji: "⌚",
    company: "Rolex",
    model: "126610LN",
    docs: 5,
    sessions: 870,
    resolutionRate: 90,
    manufacturer: "Rolex SA",
    year: "2020 - Present",
    productType: "Divers Wristwatch",
    commonIssues: ["Time drift outside +2/-2 secs", "Oysterlock clasp safety catch stiffness", "Ceramic bezel alignment click drift"],
    documentation: [
      { icon: "📘", name: "User Instruction Booklet", meta: "PDF · 32 pages · Indexed" },
      { icon: "🔧", name: "Watchmaker Service & Lubrication Reference", meta: "PDF · 56 pages · Indexed", featured: true },
    ]
  },
  {
    id: "thermomix-tm6",
    name: "Thermomix TM6 Cooker",
    category: "Appliances",
    description: "Smart all-in-one kitchen appliance capable of mixing, steaming, weighing, emulsifying, cooking, and guided online recipe integrations.",
    image_url: "https://images.unsplash.com/photo-1556911220-e15b29be8c8f",
    brand: "Vorwerk",
    price: 1499,
    rating: 4.8,
    emoji: "🍲",
    company: "Vorwerk",
    model: "TM6",
    docs: 7,
    sessions: 1890,
    resolutionRate: 91,
    manufacturer: "Vorwerk & Co.",
    year: "2022 - Present",
    productType: "Multicooker",
    commonIssues: ["Scale calibration drift", "Lid locking arm jam", "Error code C39 on boot", "Wi-Fi connection drop on Cookidoo"],
    documentation: [
      { icon: "📘", name: "TM6 User Manual", meta: "PDF · 88 pages · Indexed" },
      { icon: "🔧", name: "Diagnostic and Sensor Service Reference", meta: "PDF · 45 pages · Indexed", featured: true },
    ]
  }
];
